kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: app-backend-dev
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: app
        role: backend
        env: dev
    spec:
      containers:
      - name: backend
        image: krol/app-go:dev
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        command: ["sh", "-c", "./app -port=8080"]
        ports:
        - name: backend
          containerPort: 8080
